[workspace]

members = [
    "abci",
    "p2p",
    "proto",
    "rpc",
    "tendermint",
    "testgen",
    "pbt-gen"
]

exclude = [
    "proto-compiler"
]

[patch.crates-io]
ed25519-dalek = { git = "https://github.com/FindoraNetwork/ed25519-dalek" }
