[package]
name = "abci-test"
version = "0.19.0"
authors = ["Thane Thomson <thane@informal.systems>"]
edition = "2018"
description = """
    abci-test provides some end-to-end integration testing between
    tendermint-abci and a full Tendermint node.
    """

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
structopt = "0.3"
tendermint = { version = "0.19.0", path = "../../tendermint" }
tendermint-rpc = { version = "0.19.0", path = "../../rpc", features = [ "websocket-client" ] }
tracing = "0.1"
tracing-subscriber = "0.3.16"
tokio = { version = "1", features = ["full"] }
